# Generated by Django 4.0.3 on 2022-03-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_celerytask_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celerytask',
            name='task_id',
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='task_status',
            field=models.BooleanField(default=False),
        ),
    ]
